In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
dataset =pd.read_csv('insurance_pre.csv')
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [4]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
independent=dataset[[ 'age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [6]:
dependent=dataset[['charges']]

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel' :['rbf','poly','sigmoid','linear'], 'C' :[10,100,500,1000,2000,3000],'gamma':['auto','scale']}
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3,n_jobs=-1)
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 500, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [10]:
re=grid.cv_results_
print("The R_score value for best parameter{}:".format(grid.best_params_))

The R_score value for best parameter{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}:

In [11]:
table=pd.DataFrame.from_dict(re)

In [12]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.058225,0.003768,0.022825,0.002202,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.004055,0.013366,-0.103821,-0.095119,-0.101604,-0.056625,0.053504,43
1,0.046846,0.004411,0.008996,0.001530,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.056274,0.069532,-0.045601,-0.025079,-0.049592,0.001107,0.051309,40
2,0.062583,0.005880,0.013406,0.000838,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.049905,0.075905,-0.046585,-0.041004,-0.046507,-0.001657,0.053391,42
3,0.058226,0.007821,0.010488,0.001902,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.377969,0.479601,0.317872,0.337979,0.324422,0.367569,0.059777,33
4,0.060806,0.010389,0.022731,0.001748,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.004126,0.013244,-0.103775,-0.095165,-0.101602,-0.056634,0.053486,44
5,0.062721,0.009881,0.010429,0.003616,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.054964,0.071297,-0.046513,-0.024157,-0.049652,0.001188,0.051594,39
6,0.070943,0.009926,0.014220,0.001302,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.049644,0.076323,-0.046798,-0.040824,-0.046521,-0.001635,0.053474,41
7,0.054125,0.008542,0.008638,0.001522,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.377969,0.479601,0.317872,0.337979,0.324422,0.367569,0.059777,33
8,0.062974,0.007513,0.024963,0.001177,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.300573,0.339474,0.173708,0.217991,0.183375,0.243024,0.065733,37
9,0.060650,0.006212,0.009291,0.001997,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.540643,0.575051,0.474839,0.535730,0.424640,0.510181,0.053582,27
10,0.063543,0.010745,0.013182,0.001156,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.478364,0.561673,0.428331,0.450454,0.431701,0.470105,0.049110,30
11,0.059126,0.003331,0.009869,0.000538,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.584474,0.655818,0.553380,0.576939,0.546881,0.583498,0.038787,21
12,0.059645,0.001929,0.025956,0.000415,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.301041,0.338741,0.174086,0.217641,0.183403,0.242982,0.065542,38
13,0.052396,0.001564,0.010383,0.000617,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.537117,0.579373,0.471840,0.537966,0.424478,0.510155,0.054955,28
14,0.064195,0.003032,0.013471,0.001921,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.478930,0.563200,0.427152,0.451250,0.432199,0.470546,0.049762,29
15,0.062169,0.004964,0.009113,0.000784,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.584474,0.655818,0.553380,0.576939,0.546881,0.583498,0.038787,21
16,0.073391,0.003036,0.026572,0.001232,500,auto,rbf,"{'C': 500, 'gamma': 'auto', 'kernel': 'rbf'}",0.601529,0.640750,0.533952,0.571062,0.521847,0.573828,0.043694,26
17,0.068048,0.007176,0.010820,0.001314,500,auto,poly,"{'C': 500, 'gamma': 'auto', 'kernel': 'poly'}",0.781613,0.780025,0.754530,0.768597,0.687317,0.754417,0.034925,11
18,0.074786,0.005263,0.011667,0.001071,500,auto,sigmoid,"{'C': 500, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.434785,0.549481,0.435040,0.430290,0.425720,0.455063,0.047332,32
19,0.073608,0.004436,0.010001,0.000776,500,auto,linear,"{'C': 500, 'gamma': 'auto', 'kernel': 'linear'}",0.601152,0.599729,0.571527,0.542915,0.565263,0.576117,0.022025,23
20,0.076417,0.005683,0.025100,0.002691,500,scale,rbf,"{'C': 500, 'gamma': 'scale', 'kernel': 'rbf'}",0.601802,0.640415,0.534267,0.570844,0.521863,0.573838,0.043568,25
21,0.069460,0.005990,0.009631,0.000578,500,scale,poly,"{'C': 500, 'gamma': 'scale', 'kernel': 'poly'}",0.780516,0.780878,0.753634,0.768982,0.687296,0.754261,0.034926,12
22,0.074121,0.004404,0.014611,0.003300,500,scale,sigmoid,"{'C': 500, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.466661,0.542011,0.413211,0.459869,0.428703,0.462091,0.044535,31
23,0.066275,0.004036,0.009771,0.000700,500,scale,linear,"{'C': 500, 'gamma': 'scale', 'kernel': 'linear'}",0.601152,0.599729,0.571527,0.542915,0.565263,0.576117,0.022025,23
24,0.077021,0.001949,0.025095,0.003730,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.733044,0.746232,0.686773,0.717920,0.649158,0.706625,0.034902,14
25,0.072142,0.013327,0.009690,0.000819,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.829631,0.802622,0.799620,0.800321,0.735580,0.793555,0.031072,7
26,0.071865,0.004286,0.012139,0.001661,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.296082,0.372281,0.216401,0.291265,0.351325,0.305471,0.054387,36
27,0.069469,0.006291,0.008888,0.000771,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.605304,0.588725,0.623230,0.537931,0.616726,0.594383,0.030560,19
28,0.072499,0.004724,0.024842,0.000684,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.733334,0.745892,0.687037,0.717769,0.649174,0.706641,0.034825,13
29,0.073799,0.015330,0.009242,0.000135,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.828213,0.802622,0.799348,0.800587,0.735555,0.793265,0.030757,8
30,0.065359,0.002452,0.013008,0.000786,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.400044,0.366097,0.242217,0.288461,0.351407,0.329645,0.056742,35
31,0.064823,0.002772,0.009066,0.000709,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.605304,0.588725,0.623230,0.537931,0.616726,0.594383,0.030560,19
32,0.073840,0.002175,0.024921,0.001634,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.814076,0.781092,0.794081,0.794075,0.733656,0.783396,0.027014,10
33,0.119428,0.020106,0.009785,0.000637,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.845403,0.805639,0.816733,0.805143,0.754961,0.805576,0.029233,4
34,0.072655,0.007083,0.013259,0.000991,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.401855,-0.508082,-0.452827,-0.751013,-0.111859,-0.445127,0.205197,46
35,0.080705,0.012788,0.008365,0.001943,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.605277,0.583646,0.697368,0.532547,0.681425,0.620053,0.061555,17
36,0.079841,0.006696,0.025765,0.003524,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.814295,0.780971,0.794227,0.793983,0.733663,0.783428,0.027068,9
37,0.108825,0.004978,0.009100,0.001982,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.845581,0.805624,0.816612,0.805133,0.754962,0.805582,0.029272,3
38,0.076002,0.008872,0.014231,0.001698,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.385658,-0.537098,-0.474912,-0.477335,-0.111187,-0.397238,0.150976,45
39,0.081727,0.006671,0.009008,0.000355,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.605277,0.583646,0.697368,0.532547,0.681425,0.620053,0.061555,17
40,0.085050,0.004741,0.025360,0.001089,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.828670,0.790265,0.811049,0.812892,0.741829,0.796941,0.030140,6
41,0.176950,0.079093,0.009073,0.001635,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.846775,0.805323,0.817309,0.805191,0.758994,0.806718,0.028279,2
42,0.072670,0.003719,0.012431,0.000418,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-1.090896,-1.761043,-1.734344,-2.304377,-1.050280,-1.588188,0.469215,47
43,0.088297,0.003230,0.008867,0.000358,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.657470,0.583501,0.697875,0.529117,0.655785,0.624750,0.060379,15
44,0.079038,0.002779,0.025153,0.001427,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.828795,0.790105,0.811123,0.812857,0.741835,0.796943,0.030174,5
45,0.181165,0.082065,0.005966,0.001317,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.846874,0.805331,0.817283,0.805239,0.758988,0.806743,0.028307,1
46,0.066760,0.004489,0.010950,0.002313,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-1.761871,-2.139307,-1.704369,-2.340839,-1.048739,-1.799025,0.443311,48
47,0.085024,0.006864,0.008160,0.001320,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.657470,0.583501,0.697875,0.529117,0.655785,0.624750,0.060379,15

In [13]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 28
BMI: 33
Children: 3
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 0

In [14]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[2982730.22434096]