In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[[ 'age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [8]:
dependent=dataset[['charges']]

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel' :['rbf','poly','sigmoid','linear'], 'C' :[10,100,500,1000,2000,3000],'gamma':['auto','scale']}
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3,n_jobs=-1)
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits

C:\Anaconda-Navi\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 500, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [12]:
re=grid.cv_results_

print("The R_score value for best parameter{}:".format(grid.best_params_))

The R_score value for best parameter{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}:

In [13]:
table=pd.DataFrame.from_dict(re)

In [14]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.104644,0.027518,0.049134,0.020706,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.004055,0.013366,-0.103821,-0.095119,-0.101604,-0.056625,0.053504,43
1,0.071842,0.012340,0.012178,0.002051,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.056274,0.069532,-0.045601,-0.025079,-0.049592,0.001107,0.051309,40
2,0.078695,0.015816,0.016447,0.004520,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.049905,0.075905,-0.046585,-0.041004,-0.046507,-0.001657,0.053391,42
3,0.058688,0.009069,0.011758,0.002800,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.377969,0.479601,0.317872,0.337979,0.324422,0.367569,0.059777,33
4,0.083148,0.016036,0.035773,0.006710,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.004126,0.013244,-0.103775,-0.095165,-0.101602,-0.056634,0.053486,44
5,0.064308,0.006733,0.013769,0.002230,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.054964,0.071297,-0.046513,-0.024157,-0.049652,0.001188,0.051594,39
6,0.092582,0.013637,0.017214,0.002320,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.049644,0.076323,-0.046798,-0.040824,-0.046521,-0.001635,0.053474,41
7,0.077503,0.009240,0.011858,0.003173,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.377969,0.479601,0.317872,0.337979,0.324422,0.367569,0.059777,33
8,0.070721,0.006537,0.031058,0.003831,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.300573,0.339474,0.173708,0.217991,0.183375,0.243024,0.065733,37
9,0.056639,0.004424,0.011524,0.001064,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.540643,0.575051,0.474839,0.535730,0.424640,0.510181,0.053582,27
10,0.081826,0.004015,0.015912,0.001770,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.478364,0.561673,0.428331,0.450454,0.431701,0.470105,0.049110,30
11,0.070967,0.006858,0.010923,0.002206,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.584474,0.655818,0.553380,0.576939,0.546881,0.583498,0.038787,21
12,0.072020,0.003037,0.028830,0.004033,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.301041,0.338741,0.174086,0.217641,0.183403,0.242982,0.065542,38
13,0.066381,0.006243,0.014463,0.003571,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.537117,0.579373,0.471840,0.537966,0.424478,0.510155,0.054955,28
14,0.086360,0.007818,0.018600,0.003398,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.478930,0.563200,0.427152,0.451250,0.432199,0.470546,0.049762,29
15,0.077145,0.005515,0.014175,0.001682,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.584474,0.655818,0.553380,0.576939,0.546881,0.583498,0.038787,21
16,0.100485,0.011807,0.031631,0.005099,500,auto,rbf,"{'C': 500, 'gamma': 'auto', 'kernel': 'rbf'}",0.601529,0.640750,0.533952,0.571062,0.521847,0.573828,0.043694,26
17,0.081391,0.008631,0.011561,0.000784,500,auto,poly,"{'C': 500, 'gamma': 'auto', 'kernel': 'poly'}",0.781613,0.780025,0.754530,0.768597,0.687317,0.754417,0.034925,11
18,0.090492,0.005417,0.018696,0.001239,500,auto,sigmoid,"{'C': 500, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.434785,0.549481,0.435040,0.430290,0.425720,0.455063,0.047332,32
19,0.085439,0.005995,0.012735,0.001591,500,auto,linear,"{'C': 500, 'gamma': 'auto', 'kernel': 'linear'}",0.601152,0.599729,0.571527,0.542915,0.565263,0.576117,0.022025,23
20,0.088714,0.008429,0.031000,0.003999,500,scale,rbf,"{'C': 500, 'gamma': 'scale', 'kernel': 'rbf'}",0.601802,0.640415,0.534267,0.570844,0.521863,0.573838,0.043568,25
21,0.077018,0.005787,0.014879,0.003478,500,scale,poly,"{'C': 500, 'gamma': 'scale', 'kernel': 'poly'}",0.780516,0.780878,0.753634,0.768982,0.687296,0.754261,0.034926,12
22,0.094752,0.009824,0.016642,0.005059,500,scale,sigmoid,"{'C': 500, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.466661,0.542011,0.413211,0.459869,0.428703,0.462091,0.044535,31
23,0.093755,0.005039,0.014935,0.002992,500,scale,linear,"{'C': 500, 'gamma': 'scale', 'kernel': 'linear'}",0.601152,0.599729,0.571527,0.542915,0.565263,0.576117,0.022025,23
24,0.090641,0.006198,0.031344,0.003908,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.733044,0.746232,0.686773,0.717920,0.649158,0.706625,0.034902,14
25,0.095002,0.013655,0.011436,0.001871,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.829631,0.802622,0.799620,0.800321,0.735580,0.793555,0.031072,7
26,0.091908,0.011619,0.016380,0.002552,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.296082,0.372281,0.216401,0.291265,0.351325,0.305471,0.054387,36
27,0.084820,0.009332,0.011106,0.001808,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.605304,0.588725,0.623230,0.537931,0.616726,0.594383,0.030560,19
28,0.085419,0.005507,0.031127,0.004295,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.733334,0.745892,0.687037,0.717769,0.649174,0.706641,0.034825,13
29,0.095773,0.031785,0.013086,0.001817,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.828213,0.802622,0.799348,0.800587,0.735555,0.793265,0.030757,8
30,0.093445,0.008089,0.017372,0.002596,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.400044,0.366097,0.242217,0.288461,0.351407,0.329645,0.056742,35
31,0.083113,0.006030,0.012310,0.002525,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.605304,0.588725,0.623230,0.537931,0.616726,0.594383,0.030560,19
32,0.095173,0.007512,0.034379,0.003504,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.814076,0.781092,0.794081,0.794075,0.733656,0.783396,0.027014,10
33,0.155807,0.038713,0.013704,0.004125,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.845403,0.805639,0.816733,0.805143,0.754961,0.805576,0.029233,4
34,0.092182,0.010782,0.015124,0.002116,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.401855,-0.508082,-0.452827,-0.751013,-0.111859,-0.445127,0.205197,46
35,0.107940,0.015489,0.013949,0.003967,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.605277,0.583646,0.697368,0.532547,0.681425,0.620053,0.061555,17
36,0.097046,0.005411,0.029054,0.004759,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.814295,0.780971,0.794227,0.793983,0.733663,0.783428,0.027068,9
37,0.154928,0.016227,0.015719,0.002924,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.845581,0.805624,0.816612,0.805133,0.754962,0.805582,0.029272,3
38,0.101625,0.005089,0.016095,0.002081,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.385658,-0.537098,-0.474912,-0.477335,-0.111187,-0.397238,0.150976,45
39,0.102337,0.009375,0.010182,0.000483,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.605277,0.583646,0.697368,0.532547,0.681425,0.620053,0.061555,17
40,0.106488,0.012208,0.030524,0.003793,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.828670,0.790265,0.811049,0.812892,0.741829,0.796941,0.030140,6
41,0.217388,0.123031,0.009914,0.001463,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.846775,0.805323,0.817309,0.805191,0.758994,0.806718,0.028279,2
42,0.084922,0.006394,0.017529,0.003363,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-1.090896,-1.761043,-1.734344,-2.304377,-1.050280,-1.588188,0.469215,47
43,0.113684,0.005950,0.014213,0.002659,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.657470,0.583501,0.697875,0.529117,0.655785,0.624750,0.060379,15
44,0.102334,0.011484,0.029484,0.000816,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.828795,0.790105,0.811123,0.812857,0.741835,0.796943,0.030174,5
45,0.255496,0.095491,0.010284,0.002410,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.846874,0.805331,0.817283,0.805239,0.758988,0.806743,0.028307,1
46,0.092023,0.008245,0.016842,0.004225,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-1.761871,-2.139307,-1.704369,-2.340839,-1.048739,-1.799025,0.443311,48
47,0.126182,0.013401,0.008526,0.000743,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.657470,0.583501,0.697875,0.529117,0.655785,0.624750,0.060379,15

In [15]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 32
BMI: 40
Children: 1
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 0

In [16]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[3895309.12114895]